"""add notes model

Revision ID: ae08ad6cb140
Revises: eed0cffdae00
Create Date: 2026-03-14 15:40:02.601458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae08ad6cb140'
down_revision = 'eed0cffdae00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('oder_index')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oder_index', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
